# ICB Colours Vector
#
# The colours that are used in the ICB theme. Non-exported (used by
# other functions e.g. icb_theme_cols)
icb_theme_colours <- c(
    green = "#8cedab",
    light_blue = "#4fbff0",
    orange = "#fc8700",
    deep_navy = "#031d44",
    purple = "#b88ce3",

    nhs_blue = "#005EB8",
    light_slate = "#b2b7b9",
    charcoal = "#2c2825",
    white = "#ffffff",
    #light_charcoal = "#9d928a",
    #light_slate = "#b2b7b9",
    light_blue = "#abc0e0",
    #light_red = "#f5b2aa",

    #dark_orange = "#7c5f03",
    #dark_charcoal = "#151412",
    #dark_slate = "#343739",
    #dark_blue = "#263f66",
    #dark_red = "#901d10"
    cluster_green1 = "#28A745",
    cluster_green2 = "#1FA766",
    cluster_turquoise = "#1AA6A0",
    cluster_lightblue = "#1A92C7",
    cluster_blue = "#2E6FCA",
    cluster_darkblue = "#4E54B0",
    cluster_purple = "#6C4993",
    cluster_purplepink = "#8C4475",
    cluster_pinkorgange = "#B8484E",
    cluster_orange = "#F16522",
    
    # High-contrast palettes based on cluster colours
    
    # Cluster green-orange contrast
    contrast_green_orange1 = "#1FA766",
    contrast_green_orange2 = "#062214",
    contrast_green_orange3 = "#96ECC2",
    contrast_green_orange4 = "#F16522",
    contrast_green_orange5 = "#341303",
    contrast_green_orange6 = "#F9C1A7",
    contrast_green_orange7 = "#FE9666",
    contrast_green_orange8 = "#A66999",
    
    # Cluster orange-blue contrast
    contrast_orange_blue1 = "#F16522",
    contrast_orange_blue2 = "#341303",
    contrast_orange_blue3 = "#F9C1A7",
    contrast_orange_blue4 = "#4E54B0",
    contrast_orange_blue5 = "#1F2247",
    contrast_orange_blue6 = "#B8BBE0",
    contrast_orange_blue7 = "#9B380A",
    contrast_orange_blue8 = "#150801",
    
    # Cluster blue-purple contrast
    contrast_blue_purple1 = "#2E6FCA",
    contrast_blue_purple2 = "#091629",
    contrast_blue_purple3 = "#80A9E2",
    contrast_blue_purple4 = "#8C4475",
    contrast_blue_purple5 = "#381B2F",
    contrast_blue_purple6 = "#D8AECB",
    contrast_blue_purple7 = "#6C4993",
    contrast_blue_purple8 = "#C4B1D9",
    
    # Cluster purple-green contrast
    contrast_purple_green1 = "#6C4993",
    contrast_purple_green2 = "#150E1D",
    contrast_purple_green3 = "#C4B1D9",
    contrast_purple_green4 = "#1FA766",
    contrast_purple_green5 = "#0A4340",
    contrast_purple_green6 = "#92EEE9",
    contrast_purple_green7 = "#8C4475",
    contrast_purple_green8 = "#D8AECB"
)



#' ICB Theme Palettes
#'
#' This function returns a palette generated by colorRampPalette from one of the
#' ICB palettes
#'
#' @param palette The name of palette to use. 'cluster' is the BSOL / BC cluster colours and default.
#' @param reverse Optional: boolean value to reverse the palette
#' @param ... arguments to pass to colorRamp
#'
#' @return A colorRamp function
#' @export
#'
#' @examples
#' icb_theme_pal("cluster")
#' icb_theme_pal("bsol")
#' # or, specify a palette
#' icb_theme_pal("ics_orange")
#' # a reverse palette
#' icb_theme_pal("cluster", TRUE)
icb_theme_pal <- function(palette = c(
    "cluster",
    "bsol",
    "alternative",
    "ics_blue",
    "ics_orange",
    "ics_green",
    "ics_purple",
    "ics_navy",
    "contrast_green_orange",
    "contrast_orange_blue",
    "contrast_blue_purple",
    "contrast_purple_green"
),
reverse = FALSE,
...) {
    palette <- match.arg(palette)

    pal <- icb_theme_cols(palette = palette)

    if (reverse) pal <- rev(pal)

    grDevices::colorRampPalette(pal, ...)
}

